# -*- coding: utf-8 -*-
"""Number Plate & Vehicles Detection (Multiple Custom Objects Detection).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wRlnjn7io1I_srr2KOVJ3fpCvqtz4Cpi
"""

!pip install ultralytics

from ultralytics import YOLO
import os
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.patches as patches
from PIL import Image

import os
folder_name = "Images"
os.makedirs(folder_name, exist_ok=True) # exist_ok=True prevents an er

folder_name = "Labels"
os.makedirs(folder_name, exist_ok=True) # exist_ok=True prevents an er

Image_files = [f for f in os.listdir("Images") if f.endswith('.jpg')]
print (f"Total images: {len(Image_files)}")
print (f"first 5 images: {Image_files[:5]}")

"""!pip install -U ipywidgets"""

Annotations = os.listdir("Labels")
print(Annotations[:5])
print(f"Total annotations: {len(Annotations)}")

label_folder = "/content/Labels"
Annotations = os.listdir(label_folder) # Make sure Annotations is defined
for annotation_file in Annotations:
    txt_path = os.path.join(label_folder, annotation_file)
    try:
        with open(txt_path, "r") as f:
            lines = f.readlines()
            print(f"Processing {annotation_file}:")
            for line in lines:
                try:
                    class_id, x_center, y_center, box_width, box_height = map(float, line.split())
                    print(f"  class:{int(class_id)}, center:({x_center:.4f}, {y_center:.4f}), size:{box_width:.4f}x{box_height:.4f}")
                except ValueError:
                    print(f"  Skipping invalid line in {annotation_file}: {line.strip()}")
    except FileNotFoundError:
        print(f"Annotation file not found: {txt_path}")

#Splitting dataset in train test val sets
from sklearn.model_selection import train_test_split
import os
#Get list of images
Image_folder = "/content/Images"
images = [f for f in os.listdir(Image_folder) if f.endswith('.jpg')]
#Split 80% train 20% test
train_df, test_df = train_test_split(images, test_size=0.1, random_state=42)
#2nd split 90% train
train_df, val_df = train_test_split(train_df, test_size=0.1, random_state=42)
print(f"train: {len(train_df)}, val: {len(val_df)}, test: {len(test_df)}")

"""Creating organized folders"""

import shutil
import os

def create_split_dirs(split_name, file_list):
    split_image_dir = os.path.join("dataset", split_name, "images")
    split_label_dir = os.path.join("dataset", split_name, "labels")

    os.makedirs(split_image_dir, exist_ok=True)
    os.makedirs(split_label_dir, exist_ok=True)

    for file_name in file_list:
        # Copy image
        shutil.copy(os.path.join("Images", file_name), os.path.join(split_image_dir, file_name))

        # Copy corresponding annotation
        base_name = os.path.splitext(file_name)[0]
        label_txt_path = os.path.join("Labels", f"{base_name}.txt")
        label_xml_path = os.path.join("Labels", f"{base_name}.xml")

        if os.path.exists(label_txt_path):
            shutil.copy(label_txt_path, os.path.join(split_label_dir, f"{base_name}.txt"))
        elif os.path.exists(label_xml_path):
            shutil.copy(label_xml_path, os.path.join(split_label_dir, f"{base_name}.xml"))
        else:
            print(f"Warning: Annotation file not found for {file_name}")


create_split_dirs("train", train_df)
create_split_dirs("val", val_df)
create_split_dirs("test", test_df)

print("Dataset split and directories created successfully!")

import albumentations as A
import cv2
import matplotlib.pyplot as plt

# Define transformations
transform = A.Compose([
    A.HorizontalFlip(p=0.5),
    A.RandomBrightnessContrast(p=0.2),
    A.Rotate(limit=20, p=0.5),
    A.RandomGamma(p=0.2)
], bbox_params=A.BboxParams(format='yolo', label_fields=['class_labels']))

# Example usage
image_path = "/content/dataset/train/images/020ab551__29c19cce-pexels-lina-5624124.jpg"
image = cv2.imread(image_path)[:, :, ::-1]  # BGR To RGB
h, w, _ = image.shape

# Example pixel coordinates [x_min, y_min, x_max, y_max]
pixel_bbox = [100, 50, 300, 200]

# Convert pixel coordinates to YOLO format [center_x, center_y, width, height] normalized
yolo_bbox = [
    ((pixel_bbox[0] + pixel_bbox[2]) / 2) / w,
    ((pixel_bbox[1] + pixel_bbox[3]) / 2) / h,
    (pixel_bbox[2] - pixel_bbox[0]) / w,
    (pixel_bbox[3] - pixel_bbox[1]) / h
]

# Bounding boxes should be a list of lists or a numpy array
bboxes = [yolo_bbox]

# The number of class labels must match the number of bounding boxes
class_labels = ['Number Plate'] # Assuming the single bbox corresponds to 'Number Plate'

transformed = transform(image=image, bboxes=bboxes, class_labels=class_labels)

# You can access the transformed image and bounding boxes like this:
transformed_image = transformed['image']
transformed_bboxes = transformed['bboxes']
transformed_class_labels = transformed['class_labels']

plt.imshow(transformed_image)
plt.show()

#Draw bounding boxes on images
for bbox in transformed_bboxes:
  x1, y1, x2, y2 = map(int, bbox)
  cv2.rectangle(transformed_image, (x1, y1), (x2, y2), (255, 0, 0), 2)
  plt.imshow(transformed_image)
  plt.show()
  #visualize with bbox
  # visualize_with_bbox(transformed_image, transformed_bboxes, transformed_class_labels)

"""Integration with data loader"""

import torch

class Dataset(torch.utils.data.Dataset):
  def __getitem__(self,idx):
    #load images and boxes
    if self.transform:
      image = self.transform(image)
      boxes = self.transform(boxes)
    return image, boxes

#Verify all images have corresponding annotations
image_names ={os.path.splitext (f)[0] for f in os.listdir(os.path.join("Images"))}
label_names = {os.path.splitext (f)[0] for f in os.listdir(os.path.join("Labels"))}
print(f"Images without annotations: {image_names - label_names}")
print(f"Annotations without images: {label_names - image_names}")

#Add min_area and min_visibility params
bbox_params = A.BboxParams(format='yolo', min_area=1000, min_visibility=0.3, label_fields=['class_labels'])

from imblearn.over_sampling import RandomOverSampler

"""Bike
Bus
Car
Numberplate
Person
Truck

YAML FILE CREATION
"""

# Commented out IPython magic to ensure Python compatibility.
# #create dataset.yaml file
# %%writefile dataset.yaml
# train: /content/dataset/train/images
# val: /content/dataset/val/images
# test: /content/dataset/test/images
# 
# nc: 6
# names: ["Bike", "Bus", "Car", "Numberplate", "Person", "Truck"]

"""Model Training"""

#✅ Step 7: Train YOLOv8 Model
from ultralytics import YOLO

model = YOLO("yolov8n.pt")  # Nano version


model.train(
    data="dataset.yaml",
    epochs=100,             # Lower epochs for small dataset
    imgsz=416,             # Standard YOLO size
    batch=4,               # Small batch size
    name="Object_detection_model",
    patience=10,           # Early stopping
    lr0=0.001,             # Learning rate
    optimizer="Adam",      # Good for small datasets
    augment=True,          # Enable augmentations
    pretrained=True        # Use pretrained weights
)

"""Checking ANNOTATIONS"""

import cv2
import matplotlib.pyplot as plt
import os

def draw_yolo_boxes(image_path, txt_path, class_names=None):
    # Load image
    image = cv2.imread(image_path)

    # Check if image loading was successful
    if image is None:
        print(f"Error loading image: {image_path}")
        return

    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    h, w, _ = image.shape

    # Read YOLO annotations
    try:
        with open(txt_path, 'r') as f:
            lines = f.readlines()
    except FileNotFoundError:
        print(f"Annotation file not found for image: {image_path}")
        lines = [] # Continue processing even if annotation file is missing

    # Draw bounding boxes
    for line in lines:
        parts = line.strip().split()
        if len(parts) < 5:
            print(f"Skipping invalid line in {txt_path}: {line.strip()}")
            continue

        class_id = int(parts[0])
        x_center = float(parts[1]) * w
        y_center = float(parts[2]) * h
        box_width = float(parts[3]) * w
        box_height = float(parts[4]) * h

        # Optional: confidence score if available
        confidence = float(parts[5]) if len(parts) >= 6 else None

        # Calculate top-left and bottom-right corners
        x1 = int(x_center - box_width / 2)
        y1 = int(y_center - box_height / 2)
        x2 = int(x_center + box_width / 2)
        y2 = int(y_center + box_height / 2)

        # Draw rectangle
        color = (255, 0, 0)
        cv2.rectangle(image, (x1, y1), (x2, y2), color, 2)

        # Prepare label text
        class_names = ["Bike","Bus","Car","Numberplate","Person","Truck"] # Replace with your class names
        class_label = class_names[class_id] if class_names and class_id < len(class_names) else str(class_id)
        label_text = f"{class_label} {confidence:.2f}" if confidence is not None else class_label

        # Draw label
        cv2.putText(image, label_text, (x1, y1 - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.8, color, 2)

    # Show image
    plt.figure(figsize=(10, 10))
    plt.imshow(image)
    plt.axis('off')
    plt.show()

# Example usage
image_folder = "/content/dataset/train/images"
label_folder = "/content/dataset/train/labels"
class_names = ["Bike","Bus","Car","Numberplate","Person","Truck"] # Replace with your class names
# Get list of image files
Image_files = [f for f in os.listdir(image_folder) if f.endswith('.jpg')]

# Iterate through image files and draw boxes
for image_file in Image_files:
    image_path = os.path.join(image_folder, image_file)
    txt_file = os.path.splitext(image_file)[0] + '.txt'
    txt_path = os.path.join(label_folder, txt_file)
    draw_yolo_boxes(image_path, txt_path, class_names=class_names)

"""Load model for Inference"""

model = YOLO("/content/runs/detect/Object_detection_model6/weights/best.pt")  # Adjust path if needed

model = YOLO("/content/runs/detect/Object_detection_model_0/weights/best.pt")  # 50 epochs

model = YOLO("/content/runs/detect/Object_detection_model_0/weights/best.pt")  # Adjust path if needed changed to 55 epchs

model = YOLO("/content/runs/detect/Object_detection_model2/weights/best.pt") #100epochs

model = YOLO("/content/runs/detect/Object_detection_model_34/weights/best.pt") #50epochs img size 640

"""Run Inference on Train images"""

import os
import matplotlib.pyplot as plt
from PIL import Image

# Path to validation images
VAL_DIR = r"/content/dataset/val/images"

# Get list of validation images
val_images = [f for f in os.listdir(VAL_DIR) if f.endswith('.jpg')]

# Run inference on a few images
results = []
for img_name in val_images[:5]:  # Show predictions on first 5 images
    img_path = os.path.join(VAL_DIR, img_name)
    result = model(img_path)
    results.append(result)
    result[0].show()  # Visualize with bounding boxes

"""Runned inference on val images"""

import os
import matplotlib.pyplot as plt
from PIL import Image
import cv2
import numpy as np

# Path to validation images
VAL_DIR = r"/content/dataset/val/images"
Val_images = [f for f in os.listdir(VAL_DIR) if f.endswith('.jpg')]

# Run inference on a few images
for img_name in Val_images[:5]:
    img_path = os.path.join(VAL_DIR, img_name)
    results = model(img_path)

    # Get the first result object
    result = results[0]

    # Plot the image with bounding boxes and labels
    rendered_img = result.plot()

    # Convert BGR to RGB for matplotlib
    rendered_img_rgb = cv2.cvtColor(rendered_img, cv2.COLOR_BGR2RGB)

    # Show image
    plt.figure(figsize=(10, 8))
    plt.imshow(rendered_img_rgb)
    plt.title(f"Predictions for: {img_name}")
    plt.axis("off")
    plt.show()

    # Optional: Print detected classes and confidence scores
    for box in result.boxes:
        cls_id = int(box.cls[0])
        conf = float(box.conf[0])
        print(f"Detected: {model.names[cls_id]} with confidence {conf:.2f}")

""" 3. Evaluation Metrics (Precision, Recall, mAP)"""

# Evaluate model on validation set using your dataset.yaml
metrics = model.val(data=r"/content/dataset.yaml")

from ultralytics import YOLO

# Load your trained model
model = YOLO("/content/runs/detect/object_detector_model_v2/weights/best.pt")

# Run validation
metrics = model.val()

import matplotlib.pyplot as plt

metrics = {
    'Precision': 0.978,
    'Recall': 0.933,
    'mAP@0.5': 0.974,
    'mAP@0.5:0.95': 0.643
}

plt.figure(figsize=(8, 5))
plt.bar(metrics.keys(), metrics.values(), color='skyblue')
plt.ylim(0, 1)
plt.title('YOLOv8 Evaluation Metrics')
plt.ylabel('Score')
plt.grid(axis='y')
plt.show()

# Save results with bounding boxes
output_dir = "runs/detect/inference_results"
for img_name in Val_images[:5]:
    img_path = os.path.join(VAL_DIR, img_name)
    model.predict(img_path, save=True, project=output_dir, name="predictions", exist_ok=True)

import matplotlib.pyplot as plt
from PIL import Image
import os

pred_dir = "runs/detect/inference_results/predictions"  # Folder where YOLOv8 saved predictions

# List saved images (adjust extension if needed)
predicted_images = [f for f in os.listdir(pred_dir) if f.endswith('.jpg') or f.endswith('.png')]

# Show first 5 predicted images
for img_name in predicted_images[:5]:
    img_path = os.path.join(pred_dir, img_name)
    img = Image.open(img_path)
    plt.figure(figsize=(8, 6))
    plt.imshow(img)
    plt.title(f"Prediction: {img_name}")
    plt.axis("off")
    plt.show()

"""IOU"""

def compute_iou(boxA, boxB):
    # boxA and boxB are in [x1, y1, x2, y2] format
    xA = max(boxA[0], boxB[0])
    yA = max(boxA[1], boxB[1])
    xB = min(boxA[2], boxB[2])
    yB = min(boxA[3], boxB[3])

    interArea = max(0, xB - xA) * max(0, yB - yA)
    boxAArea = (boxA[2] - boxA[0]) * (boxA[3] - boxA[1])
    boxBArea = (boxB[2] - boxB[0]) * (boxB[3] - boxB[1])

    iou = interArea / float(boxAArea + boxBArea - interArea)
    return iou

"""OCR"""

from difflib import SequenceMatcher

def ocr_accuracy(pred_text, true_text):
    matcher = SequenceMatcher(None, pred_text, true_text)
    return matcher.ratio()  # Returns a float between 0 and 1

results = model(image)  # or model.predict(source='path/to/images')

# For a single image
total_predictions = len(results[0].boxes)

# For multiple images
total_predictions = sum(len(result.boxes) for result in results)

import os

def count_ground_truths(label_folder):
    total_gt = 0
    for file in os.listdir(label_folder):
        if file.endswith('.txt'):
            with open(os.path.join(label_folder, file)) as f:
                total_gt += len(f.readlines())
    return total_gt

"""To determine true positives, compare each predicted box to ground truth boxes using IoU. If IoU > threshold (e.g., 0.5), it's a match."""

def compute_iou(boxA, boxB):
    # Computes IoU between two boxes [x1, y1, x2, y2]
    xA = max(boxA[0], boxB[0])
    yA = max(boxA[1], boxB[1])
    xB = min(boxA[2], boxB[2])
    yB = min(boxA[3], boxB[3])

    interArea = max(0, xB - xA) * max(0, yB - yA)
    boxAArea = (boxA[2] - boxA[0]) * (boxA[3] - boxA[1])
    boxBArea = (boxB[2] - boxB[0]) * (boxB[3] - boxB[1])

    iou = interArea / float(boxAArea + boxBArea - interArea)
    return iou

def count_true_positives(predicted_boxes, ground_truth_boxes, iou_threshold=0.5):
    matched_gt = set()
    true_positives = 0

    for pred_box in predicted_boxes:
        for i, gt_box in enumerate(ground_truth_boxes):
            if i in matched_gt:
                continue
            iou = compute_iou(pred_box, gt_box)
            if iou >= iou_threshold:
                true_positives += 1
                matched_gt.add(i)
                break

    return true_positives

predicted_boxes = [[50, 50, 150, 150], [30, 30, 100, 100]]
ground_truth_boxes = [[55, 55, 145, 145], [200, 200, 300, 300]]

tp = count_true_positives(predicted_boxes, ground_truth_boxes)

false_positives = total_predictions - true_positives

false_negatives = total_ground_truths - true_positives

# You need to define these variables based on your evaluation results
# Replace the placeholder values with your actual counts
# total_predictions = 0  # Placeholder: Total number of bounding box predictions made by the model
# true_positives = 0     # Placeholder: Number of correct predictions (predictions that overlap sufficiently with a ground truth box)
# total_ground_truths = 0 # Placeholder: Total number of ground truth bounding boxes

false_positives = total_predictions - true_positives
false_negatives = total_ground_truths - true_positives

# Avoid division by zero if there are no predictions or ground truths
fp_rate = false_positives / total_predictions if total_predictions > 0 else 0
fn_rate = false_negatives / total_ground_truths if total_ground_truths > 0 else 0

print(f"False Positives: {false_positives}")
print(f"False Negatives: {false_negatives}")
print(f"False Positive Rate: {fp_rate:.4f}")
print(f"False Negative Rate: {fn_rate:.4f}")

"""Stream lit deployement"""

!pip install streamlit streamlit_option_menu  # installing streamlit and streamlit_option_menu packages

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# from streamlit_option_menu import option_menu
# from ultralytics import YOLO
# from PIL import Image
# import numpy as np
# 
# # Load YOLOv8 model
# model = YOLO("/content/runs/detect/object_detector_model_v2/weights")
# 
# # Title
# st.title("🚗 Object Detection YOLOv8")
# 
# # Upload image
# uploaded_file = st.file_uploader("", type=["jpg", "jpeg", "png"])
# 
# if uploaded_file is not None:
#     # Load image with PIL
#     image = Image.open(uploaded_file).convert("RGB")
# 
#     # Display original image
#     st.image(image, caption="Uploaded Image", use_column_width=True)
# 
#     # Convert PIL image to numpy array
#     image_np = np.array(image)
# 
#     # Run YOLOv8 prediction on the image
#     results = model.predict(image_np)
# 
#     # Extract first result and render bounding boxes
#     result = results[0]
#     rendered_img = result.plot()  # numpy array with boxes drawn
# 
#     # Display result
#     st.image(rendered_img, caption="Detected Image", use_column_width=True)
#

!wget -q -O - ipv4.icanhazip.com   # this command will generate a password for you(copy that)

! streamlit run app.py & npx localtunnel --port 8501  # replace the file name accordingly

'''
Running the above command would generate a following command

Ok to proceed?(y)  # Here you need to give y

Then a link will be generated, for example my link is 'https://fruity-aliens-unite.loca.lt/'

Paste the link in your browser, it will ask you for a password.

Paste your copied password from above, it will redirect you to your streamlit app.
'''